"""
Product Service - Product catalog microservice.

This service generates realistic product data using Faker.
It is one of the example microservices for the API Gateway.
"""

from fastapi import FastAPI, Query
from faker import Faker
from typing import List, Dict, Any

# Initialize FastAPI
app = FastAPI(
    title="Product Service",
    description="Product catalog microservice with data generated by Faker",
    version="1.0.0"
)

# Initialize Faker
fake = Faker()


@app.get("/health")
def health_check() -> Dict[str, str]:
    """
    Health check endpoint.

    Returns:
        Service status
    """
    return {"status": "healthy", "service": "product-service"}


@app.get("/api/products")
def get_products(limit: int = Query(default=10, ge=1, le=100)) -> List[Dict[str, Any]]:
    """
    Get a list of products with data generated by Faker.

    Args:
        limit: Number of products to generate (1-100)

    Returns:
        List of products with realistic data
    """
    products = []

    for _ in range(limit):
        product = {
            "id": fake.uuid4(),
            "name": fake.catch_phrase(),
            "description": fake.sentence(nb_words=10),
            "price": round(fake.random.uniform(9.99, 999.99), 2),
            "category": fake.word().capitalize(),
            "stock": fake.random_int(min=0, max=500),
            "sku": fake.bothify(text="PRD-????-####"),
            "created_at": fake.date_time_this_year().isoformat(),
        }
        products.append(product)

    return products


@app.get("/api/products/{product_id}")
def get_product_by_id(product_id: str) -> Dict[str, Any]:
    """
    Get a specific product by ID.

    Args:
        product_id: Product ID

    Returns:
        Product with generated data
    """
    # Use product_id as seed to always generate the same product
    Faker.seed(hash(product_id) % (2**32))
    temp_fake = Faker()

    product = {
        "id": product_id,
        "name": temp_fake.catch_phrase(),
        "description": temp_fake.sentence(nb_words=15),
        "price": round(temp_fake.random.uniform(9.99, 999.99), 2),
        "category": temp_fake.word().capitalize(),
        "stock": temp_fake.random_int(min=0, max=500),
        "sku": temp_fake.bothify(text="PRD-????-####"),
        "created_at": temp_fake.date_time_this_year().isoformat(),
        "manufacturer": temp_fake.company(),
        "rating": round(temp_fake.random.uniform(1.0, 5.0), 1),
    }

    return product
