"""
User Service - User management microservice.

This service generates realistic user data using Faker.
Includes profiles, addresses and authentication data.
"""

import jwt
from datetime import datetime, timedelta, timezone
from fastapi import FastAPI, Query, HTTPException
from faker import Faker
from pydantic import BaseModel
from typing import List, Dict, Any

# JWT Configuration (same as gateway)
JWT_SECRET = "dev-secret-key-change-in-production"
JWT_ALGORITHM = "HS256"

# Initialize FastAPI
app = FastAPI(
    title="User Service",
    description="User management microservice with data generated by Faker",
    version="1.0.0"
)

# Initialize Faker
fake = Faker()


class LoginRequest(BaseModel):
    """Login credentials."""
    username: str
    password: str


# Fake users database
FAKE_USERS = {
    "admin": "admin123",
    "test": "test123"
}


@app.get("/health")
def health_check() -> Dict[str, str]:
    """
    Health check endpoint.

    Returns:
        Service status
    """
    return {"status": "healthy", "service": "user-service"}


@app.post("/login")
def login(credentials: LoginRequest) -> Dict[str, str]:
    """
    User login endpoint - generates JWT token.

    Args:
        credentials: Username and password

    Returns:
        JWT access token

    Raises:
        HTTPException: If credentials are invalid
    """
    # Validate credentials
    if credentials.username not in FAKE_USERS:
        raise HTTPException(status_code=401, detail="Invalid username or password")

    if FAKE_USERS[credentials.username] != credentials.password:
        raise HTTPException(status_code=401, detail="Invalid username or password")

    # Create JWT token
    expire = datetime.now(timezone.utc) + timedelta(hours=24)
    token_data = {
        "sub": credentials.username,
        "exp": expire
    }
    token = jwt.encode(token_data, JWT_SECRET, algorithm=JWT_ALGORITHM)

    return {"access_token": token, "token_type": "bearer"}


@app.get("/api/users")
def get_users(limit: int = Query(default=10, ge=1, le=100)) -> List[Dict[str, Any]]:
    """
    Get a list of users with data generated by Faker.

    Args:
        limit: Number of users to generate (1-100)

    Returns:
        List of users with realistic data
    """
    users = []

    for _ in range(limit):
        user = {
            "id": fake.uuid4(),
            "username": fake.user_name(),
            "email": fake.email(),
            "first_name": fake.first_name(),
            "last_name": fake.last_name(),
            "phone": fake.phone_number(),
            "address": {
                "street": fake.street_address(),
                "city": fake.city(),
                "state": fake.state(),
                "country": fake.country(),
                "postal_code": fake.postcode(),
            },
            "date_of_birth": fake.date_of_birth(minimum_age=18, maximum_age=80).isoformat(),
            "created_at": fake.date_time_this_year().isoformat(),
            "is_active": fake.boolean(chance_of_getting_true=85),
        }
        users.append(user)

    return users


@app.get("/api/users/{user_id}")
def get_user_by_id(user_id: str) -> Dict[str, Any]:
    """
    Get a specific user by ID.

    Args:
        user_id: User ID

    Returns:
        User with generated data
    """
    # Use user_id as seed to always generate the same user
    Faker.seed(hash(user_id) % (2**32))
    temp_fake = Faker()

    user = {
        "id": user_id,
        "username": temp_fake.user_name(),
        "email": temp_fake.email(),
        "first_name": temp_fake.first_name(),
        "last_name": temp_fake.last_name(),
        "phone": temp_fake.phone_number(),
        "address": {
            "street": temp_fake.street_address(),
            "city": temp_fake.city(),
            "state": temp_fake.state(),
            "country": temp_fake.country(),
            "postal_code": temp_fake.postcode(),
        },
        "date_of_birth": temp_fake.date_of_birth(minimum_age=18, maximum_age=80).isoformat(),
        "created_at": temp_fake.date_time_this_year().isoformat(),
        "is_active": temp_fake.boolean(chance_of_getting_true=85),
        "job": temp_fake.job(),
        "company": temp_fake.company(),
    }

    return user


@app.get("/api/users/{user_id}/profile")
def get_user_profile(user_id: str) -> Dict[str, Any]:
    """
    Get detailed user profile.

    Args:
        user_id: User ID

    Returns:
        Extended user profile
    """
    # Use user_id as seed for consistency
    Faker.seed(hash(user_id) % (2**32))
    temp_fake = Faker()

    profile = {
        "user_id": user_id,
        "bio": temp_fake.text(max_nb_chars=200),
        "avatar_url": temp_fake.image_url(),
        "website": temp_fake.url(),
        "social_media": {
            "twitter": f"@{temp_fake.user_name()}",
            "linkedin": temp_fake.url(),
        },
        "preferences": {
            "language": temp_fake.language_code(),
            "timezone": temp_fake.timezone(),
            "newsletter": temp_fake.boolean(chance_of_getting_true=60),
        },
        "last_login": temp_fake.date_time_this_month().isoformat(),
    }

    return profile
