"""
Order Service - Order management microservice.

This service generates realistic order data using Faker.
Includes transaction information, statuses and tracking.
"""

from fastapi import FastAPI, Query, HTTPException
from faker import Faker
from typing import List, Dict, Any
from datetime import datetime, timedelta
import random

# Initialize FastAPI
app = FastAPI(
    title="Order Service",
    description="Order management microservice with data generated by Faker",
    version="1.0.0"
)

# Initialize Faker
fake = Faker()

# Possible order statuses
ORDER_STATUSES = ["pending", "processing", "shipped", "delivered", "cancelled"]

# Payment methods
PAYMENT_METHODS = ["credit_card", "debit_card", "paypal", "bank_transfer"]


@app.get("/health")
def health_check() -> Dict[str, str]:
    """
    Health check endpoint.

    Returns:
        Service status
    """
    return {"status": "healthy", "service": "order-service"}


@app.get("/api/orders")
def get_orders(limit: int = Query(default=10, ge=1, le=100)) -> List[Dict[str, Any]]:
    """
    Get a list of orders with data generated by Faker.

    Args:
        limit: Number of orders to generate (1-100)

    Returns:
        List of orders with realistic data
    """
    orders = []

    for _ in range(limit):
        num_items = fake.random_int(min=1, max=5)
        items = []
        subtotal = 0.0

        # Generate order items
        for _ in range(num_items):
            item_price = round(fake.random.uniform(9.99, 299.99), 2)
            item_quantity = fake.random_int(min=1, max=3)
            item_total = round(item_price * item_quantity, 2)
            subtotal += item_total

            items.append({
                "product_id": fake.uuid4(),
                "product_name": fake.catch_phrase(),
                "quantity": item_quantity,
                "unit_price": item_price,
                "total": item_total,
            })

        tax = round(subtotal * 0.21, 2)  # IVA 21%
        shipping = round(fake.random.uniform(5.00, 15.00), 2)
        total = round(subtotal + tax + shipping, 2)

        order = {
            "id": fake.uuid4(),
            "order_number": fake.bothify(text="ORD-########"),
            "user_id": fake.uuid4(),
            "status": fake.random_element(elements=ORDER_STATUSES),
            "items": items,
            "subtotal": subtotal,
            "tax": tax,
            "shipping_cost": shipping,
            "total": total,
            "payment_method": fake.random_element(elements=PAYMENT_METHODS),
            "created_at": fake.date_time_this_year().isoformat(),
            "updated_at": fake.date_time_this_month().isoformat(),
        }
        orders.append(order)

    return orders


@app.get("/api/orders/{order_id}")
def get_order_by_id(order_id: str) -> Dict[str, Any]:
    """
    Get a specific order by ID.

    Args:
        order_id: Order ID

    Returns:
        Order with generated data
    """
    # Use order_id as seed to always generate the same order
    Faker.seed(hash(order_id) % (2**32))
    temp_fake = Faker()

    num_items = temp_fake.random_int(min=1, max=5)
    items = []
    subtotal = 0.0

    for _ in range(num_items):
        item_price = round(temp_fake.random.uniform(9.99, 299.99), 2)
        item_quantity = temp_fake.random_int(min=1, max=3)
        item_total = round(item_price * item_quantity, 2)
        subtotal += item_total

        items.append({
            "product_id": temp_fake.uuid4(),
            "product_name": temp_fake.catch_phrase(),
            "quantity": item_quantity,
            "unit_price": item_price,
            "total": item_total,
        })

    tax = round(subtotal * 0.21, 2)
    shipping = round(temp_fake.random.uniform(5.00, 15.00), 2)
    total = round(subtotal + tax + shipping, 2)

    order = {
        "id": order_id,
        "order_number": temp_fake.bothify(text="ORD-########"),
        "user_id": temp_fake.uuid4(),
        "status": temp_fake.random_element(elements=ORDER_STATUSES),
        "items": items,
        "subtotal": subtotal,
        "tax": tax,
        "shipping_cost": shipping,
        "total": total,
        "payment_method": temp_fake.random_element(elements=PAYMENT_METHODS),
        "shipping_address": {
            "street": temp_fake.street_address(),
            "city": temp_fake.city(),
            "state": temp_fake.state(),
            "country": temp_fake.country(),
            "postal_code": temp_fake.postcode(),
        },
        "tracking_number": temp_fake.bothify(text="TRK-??########??"),
        "created_at": temp_fake.date_time_this_year().isoformat(),
        "updated_at": temp_fake.date_time_this_month().isoformat(),
    }

    return order


@app.get("/api/orders/{order_id}/tracking")
def get_order_tracking(order_id: str) -> Dict[str, Any]:
    """
    Get tracking information for an order.

    Args:
        order_id: Order ID

    Returns:
        Order tracking information
    """
    # Use order_id as seed for consistency
    Faker.seed(hash(order_id) % (2**32))
    temp_fake = Faker()

    # Generate tracking history
    tracking_events = []
    base_date = temp_fake.date_time_this_month()

    events = [
        "Order placed",
        "Payment confirmed",
        "Processing in warehouse",
        "Shipped",
        "In transit",
        "Out for delivery",
    ]

    for i, event in enumerate(events):
        event_date = base_date + timedelta(days=i)
        tracking_events.append({
            "status": event,
            "location": temp_fake.city(),
            "timestamp": event_date.isoformat(),
            "description": temp_fake.sentence(nb_words=8),
        })

    tracking = {
        "order_id": order_id,
        "tracking_number": temp_fake.bothify(text="TRK-??########??"),
        "carrier": temp_fake.random_element(elements=["DHL", "UPS", "FedEx", "USPS"]),
        "current_status": temp_fake.random_element(elements=ORDER_STATUSES),
        "estimated_delivery": (base_date + timedelta(days=7)).isoformat(),
        "events": tracking_events,
    }

    return tracking
